# Data Pre-Processing

# Importing the libraries

In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Importing the dataset

In [60]:
import os

In [61]:
os.getcwd()

'C:\\Users\\ssson\\OneDrive\\Desktop\\Machine Learning A-Z Template Folder\\Part 1 - Data Preprocessing'

In [62]:
os.chdir('C:\\Users\\ssson\\OneDrive\\Desktop\\Machine Learning A-Z Template Folder\\Part 1 - Data Preprocessing')

In [63]:
Data = pd.read_csv("Data.csv")

In [64]:
Data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [65]:
# Creating Matrix of feature of Independent Variable (Country, age, salary)

In [66]:
X = Data.iloc[:,:-1].values

# : means take all row , :-1 take all column except last one.
# .values means converting into array
# iloc - Pandas provide a unique method to retrieve rows from a Data frame. 
#Dataframe.iloc[] method is used when the index label of a data frame is 
#something other than numeric series of 0, 1, 2, 3….n or in case the user doesn't know the index label

In [67]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [68]:
Y = Data.iloc[:, 3].values

# index in python start with 0. so last column "purchase" have index no - 3

In [69]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# Handling Missing data



I will use Mean to handle my missing data


In [70]:
from sklearn.preprocessing import Imputer

# downloaded imputer class from sklearn.preprocessing library

In [71]:
imputer = Imputer(missing_values = "NaN", strategy = 'mean' , axis = 0)

#then will create object of the class and choose misising value parameter and 
#fill Nan as our data have Nan detail for missing value, and choose "Mean" as strategy.
#axis = 0 it means Means of the columns.

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [72]:
imputer.fit(X[:, 1:3])

#Fiting data - i will use imputer.fit to fit this model on independent variable. i have taken index 1 (age) index 2 (salary)


Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [73]:
# replacing missing data by mean of the column. Transform method will replace missing data.

X[:, 1:3] =  imputer.transform(X[:, 1:3])

In [74]:
X

# can see missing data replace by mean. in salry [63777.77] and in age [ 38.777]

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding Categorical Data

In [75]:
# firstly import labelencoder class from sklearn preprocessing library

from sklearn.preprocessing import LabelEncoder

In [76]:
# creating object of label encoder, and then fitting label encoder in column 0 "country"
# by applying this in X we encoded our country column in number.
# There is no hierarichal no in country so 0,1,2 does not mean order. 
# so prevent this i will use Dummy variable.


labelencoder_x = LabelEncoder()
X[:, 0] = labelencoder_x.fit_transform(X[:, 0])

In [77]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [78]:
# Dummy variable Implication

In [79]:
# Use ONE HOT ENCODER for creating Dummy Variable

In [80]:
from sklearn.preprocessing import OneHotEncoder
Onehotencoder = OneHotEncoder(categorical_features = [0])

In [81]:
X = Onehotencoder.fit_transform(X).toarray()

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Public\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [82]:
X 

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [85]:
# replacing dependent varibale (purchase) into numeric

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(Y)

In [87]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Splitting the dataset into Training and Test dataset

In [88]:
# from modelselection library import traintestsplit class

from sklearn.model_selection import train_test_split

In [89]:
# remember this should always in this sequence x train xtest ytrain y test.
# split data in 80 :20 ratio.
# random state will help to give same result everytime

x_train, x_test , y_train , y_test = train_test_split(X, y , test_size = 0.2, random_state = 0)


In [90]:
x_train

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04]])

In [91]:
x_test

array([[0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04]])

In [92]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [93]:
y_test

array([0, 0])

# Feature Scaling

feature scaling use for creating every variable into same scale, another it will give bad model result.
like we have salary and age kind of variable which euclidean distance will create huge difference and salary result will overlap age result. or it helps to do faster implementation .

TYPE _

STANDARDISATION

NORMALIZATION

In [94]:
# from sklearn preprocessing library imprt standard scaler class

from sklearn.preprocessing import StandardScaler

In [98]:
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test) 


# do we need to scale dummy variables too - it depends on the context. if we scale this everything on the same parameter.
# test model do not need to fit as it already fitted to training set.
# WE DO NOT NEED TO SCALE Y TRAIN IN FEATURE SCALING AS THERE ONLY TWO CATEGORIAL VALUE YES OR NO. THIS IS CLASSIFICATION PROBLEM.
# IN CASE OF REGRESSION WE CAN USE FEATURE SCALING IN Y TRAIN AND Y TEST.

In [99]:
x_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [100]:
x_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])